# Generated by Django 6.0.4 on 2026-04-21 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('citizenship_no', models.CharField(max_length=16)),
                ('issued_district', models.CharField(max_length=50)),
                ('permanent_address', models.CharField(max_length=50)),
                ('citizenship_front', models.ImageField(blank=True, null=True, upload_to='citizenship')),
                ('citizenship_back', models.ImageField(blank=True, null=True, upload_to='citizenship')),
                ('email_verified', models.BooleanField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending')),
                ('kyc_verified', models.BooleanField(choices=[('not_submitted', 'Not Submitted'), ('in_review', 'In_review'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='not_submitted')),
                ('rejection_reason', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
