# Generated by Django 6.0.4 on 2026-04-22 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='citizenship_no',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_verified',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='issued_district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kyc_verified',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('in_review', 'In_review'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='not_submitted'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permanent_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
