# Generated by Django 6.0.4 on 2026-04-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_citizenship_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='speciality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kyc_verified',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('in_review', 'In review'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='not_submitted'),
        ),
    ]
